include: package:flutter_lints/flutter.yaml

linter:
  analyzer:
    errors:
      invalid_annotation_target: ignore
  rules:
    - prefer_relative_imports
    - analyzer:
        errors:
          invalid_annotation_target: ignore
analyzer:
  error:
    invalid_annotation_target: ignore